language: cpp
dist: trusty
sudo: enabled
compiler: gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-5
  - export CC=gcc-5
  - export CXX=g++-5

  - sudo apt-get install doxygen g++-5 libboost-filesystem-dev libboost-program-options-dev libboost-random-dev libboost-thread-dev libprotobuf-dev protobuf-compiler zlib1g-dev -y

  - wget https://github.com/viproma/debian-fmilib/releases/download/debian%2F2.0.2-1/libfmilib2_2.0.2-1_amd64.deb
  - wget https://github.com/viproma/debian-fmilib/releases/download/debian%2F2.0.2-1/libfmilib2-dev_2.0.2-1_amd64.deb
  - sudo dpkg -i libfmilib2_2.0.2-1_amd64.deb libfmilib2-dev_2.0.2-1_amd64.deb

  - wget http://mirrors.kernel.org/ubuntu/pool/universe/libz/libzip/libzip4_1.1.2-1.1_amd64.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/libz/libzip/libzip-dev_1.1.2-1.1_amd64.deb
  - sudo dpkg -i libzip4_1.1.2-1.1_amd64.deb libzip-dev_1.1.2-1.1_amd64.deb

install:
  - ZEROMQ_VERSION=4.1.3
  - curl -fsSL http://download.zeromq.org/zeromq-${ZEROMQ_VERSION}.tar.gz | tar -zxf -
  - pushd zeromq-${ZEROMQ_VERSION}
  - ./configure --without-libsodium && make && sudo make install -j2
  - popd

script: cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCORAL_ENABLE_TRACE_LOGGING=TRUE. && cmake --build . && ctest -V
